"""added uniqueness in review

Revision ID: eb5d6f6867de
Revises: 64761b04b9aa
Create Date: 2025-11-11 00:17:01.503062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb5d6f6867de'
down_revision: Union[str, Sequence[str], None] = '64761b04b9aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_user_book_review', 'reviews', ['user_id', 'book_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_book_review', 'reviews', type_='unique')
    # ### end Alembic commands ###
